version: "3.8"
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    #env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  grademanager:
    depends_on:
      - mysql
    restart: on-failure
   # env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/test?useSSL=false",
        "spring.datasource.username" : "test",
        "spring.datasource.password" : "test",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: